name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: HeavenCube/HCPlugins-actions/.github/workflows/build.yml@main
    with:
      project-name: HCItemFrame
      artifact-path: build/libs/HCItemFrame-*.jar
      core-source: true
      source-repositories: HeavenCube/HCPack-CustomGlowing
    secrets: inherit
